// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATezXPWXJD6Ht4GcLrzOTh4Rfg8Lzjz_Y',
    appId: '1:90862331713:web:16ac269ac85e4cd929e3c0',
    messagingSenderId: '90862331713',
    projectId: 'flutter-login-app-7289d',
    authDomain: 'flutter-login-app-7289d.firebaseapp.com',
    storageBucket: 'flutter-login-app-7289d.firebasestorage.app',
    measurementId: 'G-3C4BBMMPZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI732Ix1kH_hadbKO_Z3cek8p_5qd20fw',
    appId: '1:90862331713:android:28370b6364497a9729e3c0',
    messagingSenderId: '90862331713',
    projectId: 'flutter-login-app-7289d',
    storageBucket: 'flutter-login-app-7289d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALeHl2mqErKDVdSUccwWGwQUC5H-91RdM',
    appId: '1:90862331713:ios:c6f161d85aeecf4d29e3c0',
    messagingSenderId: '90862331713',
    projectId: 'flutter-login-app-7289d',
    storageBucket: 'flutter-login-app-7289d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALeHl2mqErKDVdSUccwWGwQUC5H-91RdM',
    appId: '1:90862331713:ios:c6f161d85aeecf4d29e3c0',
    messagingSenderId: '90862331713',
    projectId: 'flutter-login-app-7289d',
    storageBucket: 'flutter-login-app-7289d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATezXPWXJD6Ht4GcLrzOTh4Rfg8Lzjz_Y',
    appId: '1:90862331713:web:3eda6765d3aaf52129e3c0',
    messagingSenderId: '90862331713',
    projectId: 'flutter-login-app-7289d',
    authDomain: 'flutter-login-app-7289d.firebaseapp.com',
    storageBucket: 'flutter-login-app-7289d.firebasestorage.app',
    measurementId: 'G-FMGR80FDW2',
  );
}
